apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactdemoseven-reactdemoms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactdemoseven-reactdemoms
  template:
    metadata:
      annotations:
        redeploy: 'true'
      labels:
        app: reactdemoseven-reactdemoms
    spec:
      containers:
      - image: 672072155362.dkr.ecr.us-east-1.amazonaws.com/reactdemoseven:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 180
          periodSeconds: 5
        name: reactdemoseven
        ports:
        - containerPort: 5173
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reactdemoms-service
spec:
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: reactdemoseven-reactdemoms
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: 'true'
  name: my-aws-ingress-class
spec:
  controller: ingress.k8s.aws/alb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/load-balancer-name: reactdemoseven-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0edd606f8c0d403b0, subnet-0576ea9d88937f2e0
    alb.ingress.kubernetes.io/success-codes: 200-404
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  labels:
    app: app-reactdemoseven
  name: ingress-reactdemoseven
spec:
  defaultBackend:
    service:
      name: reactdemoms-service
      port:
        number: 5173
  ingressClassName: my-aws-ingress-class
